package io.menio.android.utilities

/**
 * Created by Amin on 30/05/2018.
 */
class ConstantsKotlin {

    val LOG_TAG = "AMIN LOG"
    val TABLE_NUMBER = "TABLE_NUMBER"
    val ACCESS_TOKEN = "ACCESS_TOKEN"
    val SELECTED_MENU = "SELECTED_MENU"
    val SELECTED_MENU_ID = "SELECTED_MENU_ID"
    val SELECTED_BRANCH = "SELECTED_BRANCH"
    val SELECTED_BRANCH_ID = "SELECTED_BRANCH_ID"
    val SELECTED_BRANCH_NAME = "SELECTED_BRANCH_NAME"
    val SELECTED_LANGUAGE = "SELECTED_LANGUAGE"
    val SELECTED_CURRENCY = "SELECTED_CURRENCY"
    val SELECTED_CURRENCY_NAME = "SELECTED_CURRENCY_NAME"
    val SELECTED_CURRENCY_CODE = "SELECTED_CURRENCY_CODE"
    val SELECTED_CATEGORY = "SELECTED_CATEGORY"
    // intent tags:
    val NAME = "NAME"
    val USER = "USER"
    val LAST_NAME = "LAST_NAME"
    val SEX = "SEX"
    val MARITAL = "MARITAL"
    val DISPLAY_NAME = "DISPLAY_NAME"

}